steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      # https://cloud.google.com/functions/docs/deploying/filesystem?hl=ja#deploy_using_the_gcloud_tool
      # gcloud functions deploy NAME --runtime RUNTIME TRIGGER [FLAGS...]
      - functions
      - deploy
      - user
      - --entry-point=CreateUser
      - --runtime=go113
      - --source=./user
      - --trigger-http
      - --region=asia-northeast1
